/** Extended admin roles for the TurboCore platform. */
export const ADMIN_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMINISTRATOR: "ADMINISTRATOR",
  FINANCE_OFFICER: "FINANCE_OFFICER",
  COMPLIANCE_OFFICER: "COMPLIANCE_OFFICER",
  SUPPORT_OFFICER: "SUPPORT_OFFICER",
  OPERATIONS_OFFICER: "OPERATIONS_OFFICER",
  RISK_OFFICER: "RISK_OFFICER",
  DEVELOPER: "DEVELOPER",
  AUDITOR: "AUDITOR",
  READONLY_ANALYST: "READONLY_ANALYST",
} as const;

export type AdminRole = (typeof ADMIN_ROLES)[keyof typeof ADMIN_ROLES];
