import { cookies } from "next/headers";

/**
 * CSP NONCE — per-request, cryptographically random.
 *
 * The nonce is generated by middleware (Edge Runtime) and stored in an
 * HttpOnly cookie so the root layout (Node Runtime) can read it. The
 * same nonce is embedded in the Content-Security-Policy header, allowing
 * only scripts with the matching `nonce="..."` attribute to execute.
 *
 * Flow:
 *   1. middleware.ts generates a 16-byte random nonce (base64url).
 *   2. Sets it as an HttpOnly cookie: `tp_csp_nonce`.
 *   3. Sets the CSP header with `script-src 'self' 'nonce-<value>'`.
 *   4. Root layout reads the cookie and passes the nonce to `<html>`.
 *   5. Next.js injects the nonce on its inline scripts.
 */

const NONCE_COOKIE = "tp_csp_nonce";
const NONCE_BYTES = 16;

/**
 * Generate a CSP nonce (base64url-encoded, 16 bytes = 22 chars).
 * Uses the Web Crypto API (Edge-compatible).
 */
export function generateNonce(): string {
  const array = new Uint8Array(NONCE_BYTES);
  crypto.getRandomValues(array);
  return base64url(array);
}

/**
 * Read the CSP nonce from the cookie set by middleware.
 * Returns the nonce string, or undefined if the cookie is missing.
 * Must be called from a Server Component / layout (has access to cookies).
 */
export async function getNonceFromCookie(): Promise<string | undefined> {
  const c = await cookies();
  return c.get(NONCE_COOKIE)?.value;
}

/** Cookie name for the CSP nonce. */
export const CSP_NONCE_COOKIE = NONCE_COOKIE;

/** Base64url encode a Uint8Array. */
function base64url(bytes: Uint8Array): string {
  let binary = "";
  for (const byte of bytes) {
    binary += String.fromCharCode(byte);
  }
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
